name: minio_new
description: Unofficial MinIO Dart Client SDK that provides simple APIs to access any Amazon S3 compatible object storage server.
version: 1.0.2
homepage: https://github.com/xtyxtyx/minio-dart
issue_tracker: https://github.com/xtyxtyx/minio-dart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.10.0
  http: ^1.1.2
  crypto: ^3.0.2
  convert: ^3.1.1
  xml: ^6.5.0
  buffer: ^1.2.2
  intl: ^0.19.0
  mime: ^1.0.2
  path: ^1.8.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
